### ISSUE TITLE
Bubbles misalign if scale is not 100%

### ISSUE THREAD

**Issue by ericthomasca** [urbanyeti/stardew-better-friendship#29]
If the UI scale is not100%, the bubbles move to the right if over 100% and to the left if under, making them not over the animals heads anymore. Same bug on Better Friendship, putting issue there too.

**Comment by urbanyeti** [comment]
I think this is caused by an issue with SMAPI or SDV itself, not much I can do at this point but there is an open issue to address it: https://github.com/Pathoschild/SMAPI/issues/936
